### ISSUE TITLE
Extract covariance matrix from VBGMMARD

### ISSUE THREAD

**Issue by MetaDev** [AmazaspShumik/Mixture-of-Experts-Models#13]
I would like to be able to sample from a fitted VBGMMARD. For this I would need the weights, means and covariances of the fitted model. The first 2 are available but I can't find the covar. I think it can be derived from the scale, but I don't know exactly how.

**Comment by AmazaspShumik** [comment]
Hi,

Take a look at my other repository, you can find VBGMMARD implementation with scikit-learn API there: https://github.com/AmazaspShumik/sklearn_bayes/blob/master/sklearn_bayes/mixture/mixture.py

After fitting model you can use instance variables for sampling:

# fit model

vbgmmard = VBGMMARD()
vbgmmard.fit(X)

# access means, weights, covariance

means   = vbgmmard.means_ # numpy array of means
weights = vbgmmard.weights_  # bumpy array of weights
covars   = vbgmmard.covars_   # list of covariances corresponding to each cluster
